table: directus_deployments

fields:
  - field: id
    special:
      - uuid
  - field: provider
  - field: credentials
    special:
      - encrypt
  - field: options
    special:
      - cast-json
  - field: projects
    special:
      - o2m
  - field: date_created
    special:
      - date-created
      - cast-timestamp
  - field: user_created
    special:
      - user-created
