blank_issues_enabled: false
contact_links:
  - name: Report App Bug
    url: https://github.com/directus/app/issues/new?labels=bug&template=bug_report.md
    about: Ask questions and discuss with other community members
  - name: Report API Bug
    url: https://github.com/directus/api/issues/new?labels=bug&template=bug_report.md
    about: Ask questions and discuss with other community members
  - name: Request Feature
    url: https://github.com/directus/directus/discussions/new
    about: Request a feature to be added to the platform
  - name: Ask a Question
    url: https://github.com/directus/directus/discussions/new
    about: Ask questions and discuss with other community members
  - name: Report Security Vulnerability
    url: support@directus.io
    about: Please report security vulnerabilities here
