name: Auto-Merge Translations from Crowdin

on:
  pull_request:
    branches:
      - main
    # Only run if pull request includes changes in translation files
    paths:
      - 'app/src/lang/translations/*.yaml'

jobs:
  auto-merge:
    name: Auto-Merge
    # Only auto-merge if it looks like an actual pull request from Crowdin
    if: github.event.pull_request.user.login == 'rijkvanzanten' && github.event.pull_request.title == 'New Crowdin updates' && github.head_ref == 'translations'
    runs-on: ubuntu-latest
    steps:
      - name: Auto-Merge
        uses: pascalgn/automerge-action@v0.14.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_LABELS: ''
          UPDATE_LABELS: ''
          MERGE_METHOD: squash
