on:
  repository_dispatch:
    types:
      - linear-command

jobs:
  create_issue:
    runs-on: ubuntu-latest
    steps:
      - uses: rijkvanzanten/gh-action-linear@v0.3.2
        with:
          github-repo: ${{ github.event.client_payload.github.payload.repository.full_name }}
          github-issue: ${{ github.event.client_payload.github.payload.issue.number }}
          linear-api-key: ${{ secrets.LINEAR_API_KEY }}
          linear-team-id: ${{ secrets.LINEAR_TEAM_ID }}
          linear-status-opened: ${{ secrets.LINEAR_STATUS_OPENED }}
          linear-status-closed: ${{ secrets.LINEAR_STATUS_CLOSED }}
          linear-status-reopened: ${{ secrets.LINEAR_STATUS_REOPENED }}
          linear-issue-label: ${{ secrets.LINEAR_ISSUE_LABEL }}
